### ISSUE TITLE
Google Play link is broken

### ISSUE THREAD

**Issue by ahstro** [jackv24/ComicWrap-F#9]
The Google Play link isn't working. Guessing the app just isn't available yet, so this is more me saying "hey, this looks really cool and I'm hyped to use it (and I can't figure out how to build with Flutter 🙄)” than anything else.

**Comment by jackv24** [comment]
Hey thanks for checking it out!

The Google Play link should be working (works for me in private browsing mode). What country are you in? I've got the beta open to a handful of countries I know are English speaking since it's not localised, but I could open it up to more.

**Comment by jackv24** [comment]
I've just checked all countries, so it should work now! (or soon)

**Comment by ahstro** [comment]
Cool, works now! Thanks, this is exactly what I needed! 💓
